#Settings
title: Roleplay Book
email: contact@benbuckton.com
description: "Set of open roleplay rules for print and digital viewing"
url: ""
markdown: kramdown

partials:
  - "_includes"

collections:
  chapters:
    output: true
  appendices:
    output: true
